### ISSUE TITLE
Github CI fails on download

### ISSUE THREAD

**Issue by Ondraceq** [paradise-fi/RoFI#145]
Github CI sometimes fails on the setup phase of `rofiFirmware` (for me it happened twice on the `Release` compilation).

```
WARNING: Download failure HTTP Error 503: Backend unavailable, connection timeout
Extracting /work/build.deps/esp-tools/dist/xtensa-esp32-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/tools/xtensa-esp32-elf/esp-2021r2-8.4.0
WARNING: Failed to download https://github.com/espressif/crosstool-NG/releases/download/esp-2021r2/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/dist/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz.tmp
Installing xtensa-esp32s2-elf@esp-2021r2-8.4.0
Downloading xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/dist/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz.tmp
WARNING: Download failure HTTP Error 503: Backend unavailable, connection timeout
WARNING: Failed to download https://github.com/espressif/crosstool-NG/releases/download/esp-2021r2/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/dist/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz.tmp
Downloading xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/dist/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz.tmp
WARNING: Download failure HTTP Error 503: Backend unavailable, connection timeout
Downloading xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/dist/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz.tmp
WARNING: Failed to download https://github.com/espressif/crosstool-NG/releases/download/esp-2021r2/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz to /work/build.deps/esp-tools/dist/xtensa-esp32s2-elf-gcc8_4_0-esp-2021r2-linux-amd64.tar.gz.tmp
ERROR: Failed to download, and retry count has expired
Traceback (most recent call last):
  File "/work/build.deps/esp-idf/tools/idf_tools.py", line 1818, in <module>
    main(sys.argv[1:])
  File "/work/build.deps/esp-idf/tools/idf_tools.py", line 1814, in main
    action_func(args)
  File "/work/build.deps/esp-idf/tools/idf_tools.py", line 1461, in action_install
    tool_obj.download(tool_version)
  File "/work/build.deps/esp-idf/tools/idf_tools.py", line 714, in download
    raise DownloadError()
```

**Comment by yaqwsx** [comment]
Resolved with e90a80602da2658777b81cba448ca0a95d871b8c
